##name
##description
##environment
##dependencies
##dev_dependencies
##flutter


name: valloon
description: A new Flutter project.

publish_to:

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  share_plus: ^3.1.0
  get: ^4.1.4
  flutter_svg: ^1.0.3

  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.4.0+1
  flutter_datetime_picker: ^1.5.1
  font_awesome_flutter: ^10.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    - lib/images/

